[project]
name = "analytics"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "boto3>=1.43.13",
    "dbt-duckdb==1.10.1",
    "duckdb>=1.5.1",
    "fastapi[standard]>=0.136.0",
    "numpy>=2.4.4",
    "pandas>=3.0.2",
    "plotly>=6.7.0",
]

[dependency-groups]
dev = [
    "pytest>=8.0",
]
