apiVersion: v1
kind: Secret
metadata:
    name: actual-openid
    namespace: apps-actual
type: Opaque
stringData:
    ACTUAL_OPENID_CLIENT_ID: ENC[AES256_GCM,data:B9s75M/4ZBaCu/Z1iTs2CaxbwHtf2D5MsANq+4i+PAqUYpETNJXVy1XoSKkp8cVYO2nsqWhhup3Bp+gCQBLd0IDZ6JWVOfqs,iv:rEfpHZqRMl+RdnKb26rVmhfG106wVJ1Ihw/nnq5SAOA=,tag:V+ELlzTN0V9F9t3dU07eBw==,type:str]
    ACTUAL_OPENID_CLIENT_SECRET: ENC[AES256_GCM,data:/fzGRBPSOtRo0BH3t9zGpTB+07wP2PGgIyqPDULYQvb4Y6s=,iv:7rtJH7Mz/twuIB4K53vGGP1F+Dz3XGFNs6dMXU78xJc=,tag:A3R+Wyg3eJUJr2egs4xBvQ==,type:str]
sops:
    age:
        - recipient: age1l554jhzkcyzu826w2a6nlczjzsfqgl29lwuntu9t3ydmfuwwucfqjgcyza
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBcWU0aVRKWm5CM3kva2ZE
            cEtWWER4K2xObnIwaWl2L1ZBU2hTSDZucmxZCkQ3N0phY1kwUkgxempGMFlobXFU
            QmpKSXVrWS9sWEIzYW1MR1BvZXNncm8KLS0tIEZORzVjY0JCem10ZzJmZnNEMnJW
            M2pmVXV4aU1lM3hJTlRlTWlWNHljU00Kt7J8VhGV2wKM0GlzpPeAIi2GtYhB/uPs
            bg61YmoG1eCB5cvrDl1fE4XwMDN4cqmMtO4suCTpOyGJ48vtALs+cA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T10:42:45Z"
    mac: ENC[AES256_GCM,data:oOhjnY9+u5ACbCHtHueXWCOT89M3Z/r18p1C89zLJ5/qzZzyiqAJvqLyrJ35R2tcoHDWNlUEJ3Nr6TobiQiJggXyIoo0TppnpAJnlAMUr12xqA+uXwyErPi3KLlXXtPylbdIJH414tmkTkHQYnDY8G9KRXhbU4KYUBhIkku21gs=,iv:yzLBH0UE+aC3663le9ey+zTIYgfc0SwRfBXnYWgVB/Y=,tag:e3Tmp2YYC3q2B/tfti8Zaw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
