apiVersion: v1
kind: Secret
metadata:
    name: actual-openid
    namespace: apps-actual
type: Opaque
stringData:
    ACTUAL_OPENID_CLIENT_ID: ENC[AES256_GCM,data:YiCrQJW/1Y2UgEjxclC0bhFL69B053o+iV1+TrjvjHCQvZp/GcPSUlx1ix3ycbcirZ0TXaMTbFaYbUanfkmNfOEw1p4mKGrs,iv:53SO0/SHtNExzkbMZ3wK6IILzl5+9x680dLPCa2cd9A=,tag:8tnlBW9/9D0RaF2Gq42ncg==,type:str]
    ACTUAL_OPENID_CLIENT_SECRET: ENC[AES256_GCM,data:pT4fALv//9bTsFk2Jf5xQVBTEpT90jaHrdIJpBIHU0C6VuU=,iv:kVCUZ7uoJOm+l+vmt8Mv8izbRDzPCicNt98TbAAHnvg=,tag:4Pv2YXa68gppkHRLQ8tlWA==,type:str]
sops:
    age:
        - recipient: age1l554jhzkcyzu826w2a6nlczjzsfqgl29lwuntu9t3ydmfuwwucfqjgcyza
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2c1NuenU4Q3lGbjRucjFn
            OXR4eFRtUXdNb2RqRlA3NldlL202d0gvL3pjClpCb2tXNTF6M1VITEJ3MUh4Rm1H
            WmZjOFQ4RXI0WGZ4WlBIN1ZlZkZ4bXMKLS0tIENpQzVadjk2MDdZLzVnMXNLZG5I
            YlV5eGZBY1dWVnpheHI1Y0M1SDYvWWcK0Sy0/GBV9DYgalG6ICS+o4wSBaPr+4Mj
            oZDXvd/ruE/IxazcceBa5U2HcH3gkpwOR3EYxvpmGDOoW8swi5v+ug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T13:28:42Z"
    mac: ENC[AES256_GCM,data:pB2W9X4f6vmOddgPd4vrtySckV3ATyPtKPF0HAPvn4PJrO4h9TusjvEiJtRjoJMbD1VkjrY0lQFJBl12xi2eMZdDjmjpmcSWXBsGnGbhbVuj4+rYz6+L+wYN9VY2/HJN+Q4d2UL6U1lKMomM5VwjD1fuu/hsXo/xIEwnxDCfWD4=,iv:n0i+MUFkj8/BRnjOql3vOcnJUhvDTV8vvfxYsokMFb4=,tag:Rz6oTix0UlJc6qoztgcjCQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
