apiVersion: v1
kind: Secret
metadata:
    name: analytics-s3
    namespace: analytics
stringData:
    S3_ENDPOINT_URL: ENC[AES256_GCM,data:XOyUdNiQqJ1bk16yN0cEM7dc8u2RJ/mYmfnwRjTUtt+z9F4=,iv:SkHDWZ0v5bpW9pODPZCCdSLr9ok2MbB2xmky/FtE128=,tag:h7NADWTOFTeN6/gp7xrmjQ==,type:str]
    S3_BUCKET: ENC[AES256_GCM,data:341kZSosaFPEcb7m8AgQ6UNv,iv:KrjRm/aDMbO2dqCO7+cT7h9DkW/KYglOfTNyy6qUBvU=,tag:TNs070eDIGR7s0la/9ECqA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:vo7vqw8wsCK/JXTpvsYJJTvD46c=,iv:P3L4EBhS6eWhxTYXjsRet89zdGvj3jQ1ukQK1F7DbvI=,tag:v8SFAywekBqHQpsAw9vaCg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ct53GxBqbOBRyK1Zg3j4XTJHipYprSR02LsF9art0TkEhlbzfAwhmQ==,iv:yVzwnzHpwCQMG1ipjnq+82RZwpyRUwfsimPkiDvt3cw=,tag:sgrJaMBcNvFtvImQOuq76g==,type:str]
sops:
    age:
        - recipient: age1l554jhzkcyzu826w2a6nlczjzsfqgl29lwuntu9t3ydmfuwwucfqjgcyza
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPdUl3OTAyaVdpbXlVKzkw
            eWFJSEplMWduRUhVZnVuUCtONFRRaTFpY0RJCjY4OVRhR0dUNEJFeXlFZy9mckJQ
            ZlkvbU1IUFVoM3c4WWJNeXF5Y3ZoWmsKLS0tIDRnMVB3Yjh2T3FQSmlodFIyRStn
            YXdyM2xqamQzMUYrMmo1NGZtOWdvZlUKrbuaEXSFKWOe5VTExpx8JzJ777tU90C6
            Cko6VsrfCrCcHvMVHB+KDjldyoB08UFXSOGFtQKACPBZZnvhzWHB3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T15:20:48Z"
    mac: ENC[AES256_GCM,data:j0N47zbwTo+olLv2RcfflhiJyY5hYUjIdzDFLddOPRRM2pCyTMIGvFpihQsN6PdEYT25oKZ80tm4iOlyj+JQYPco1eC1K67gJ55fbNAhn8FyqQNCKLkOOsLIAbqfF1J1LLFXdYelP6V7KoATXJSIHjDZpGr0RKT1GjiDSKprapY=,iv:hkJjgZp6dSQ/VVPsMKxVkxHS8Vl4C0fZauCiUWuhLuo=,tag:O1iIxoJIM/YJ4hcIBNMLHA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
