apiVersion: v1
kind: Secret
metadata:
    name: postgres-analytics-s3
    namespace: infra-postgres
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:JCvBZM7G+UQE/8TVMIVtG0eiaxc=,iv:Qa5mi5jqYNfxHlNYgHJJIvGVp8ppAE6mvCFnebNupfA=,tag:9hdz039Nw9OLrhZND+X1zg==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:7VABiUNeDUmZY07/yfaxFa7Vaf4mU3bq3is05iEWRc/WqC/SBH+aqg==,iv:1D1NtscsqMlTSwKy8joBMWAdYetGwwm1Z+tg339KxcE=,tag:O388XxRRvkw+rHgJR6Fqzw==,type:str]
sops:
    age:
        - recipient: age1l554jhzkcyzu826w2a6nlczjzsfqgl29lwuntu9t3ydmfuwwucfqjgcyza
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMZWltT0FETkVTTkdDMzc0
            YklISmp6YUJIZ09ONjQ0ZUV5OWRWK0psNVdnCkVld3FNOXduRmR2ZHV3ZTQrZWRR
            c21wQlVTSXdFNXZad0lXbGFsQ0R3ZG8KLS0tIHFmMmplWHRSa1Zmdm9ya3B0RG1K
            REI4SHZYM0phYVdsNTlXN2lIdHpJYU0Kh/+43GM/NBWttlnLHFbG5hv3uy9l1DoV
            zogPmQldoSHIqVTd/QcJzqpNM1aDS7//D5gZOuXgeUyEjdpIcqMS5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-03T08:53:11Z"
    mac: ENC[AES256_GCM,data:28kkMgKPSwbK3/ufluypPDYoxjgvbD3kYveHW4RbBQbX3JxxFROBQ6JD6DzBK5N848eQNSZ20EleFFO5ngS4/iGR7G60RSX4w0hWpmlD1AWuy+GFwuTaiGRLsNLMIV+5bpS8CP8YZ4Oq1zgeW+OydpCu4Qz2gYiHACO/nmYlI2A=,iv:MkXvWNAxfkb01y2GQEycPfVzz21QDDo7d/2UejUg9Z0=,tag:lTSD+YQi5SdqsCt049UHvw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
