apiVersion: v1
kind: Secret
metadata:
    name: demo-secret
    namespace: default
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:eM01j5G1Ibs=,iv:ofFE68Ie4LJqhlMf0aIXiAF++n8DBeXlxsPRK79TT6c=,tag:QdqgaY/8SvIx3s06e35ODQ==,type:str]
    password: ENC[AES256_GCM,data:WU8BVvT+hNT88tojtWc=,iv:wfBgEkIxKtw3272BWXYlBjoVK2XARIV31CoW6wWMSLE=,tag:zU38MIQ2X5I98st+err5Aw==,type:str]
sops:
    age:
        - recipient: age1l554jhzkcyzu826w2a6nlczjzsfqgl29lwuntu9t3ydmfuwwucfqjgcyza
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpRVQrUmN0ZFp6R3h1eVhq
            YllmNktkVUUwa0V0eUtQbGtLZ2cxVHhjcFdBCnY1U1k0OUpCd3NBOG1DM1hpUGFH
            Ky90b2tLczB5ZjY4NlNtOHVvc0dCZVUKLS0tIHlzdDFrOTgvRWN1VUxvY2Q4anBS
            Z1NlNC84OEFsUHBsa29OU3FtdWk4cDQKZkPfSN9MkrNMEW7NnWQdGuILRxHYoFAW
            TDxebvt+r3aGIXUdGviCFyWvrcB5uK9eu2RD2xfnmy1XmJjAi61JKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T08:22:32Z"
    mac: ENC[AES256_GCM,data:hs6YBs+rTzWEvQf1faDqeAVZVpetkaB6aq9LU1ciKKnsVxNCeR16ocZUBE5e71I3fBfGz+carvdLfs5wWyBVkiBDOtF30OqXZvOzlp7MnCw5hupnDHKEsXslO4AdrdmfeiHD/ugcw3mBaZJyMm/bbWjg/MImwyb7XR5K1DLomS8=,iv:YNDjHtT2K5FnZaiPDrd+ySH9n/gHqmgjvc3sAEaAd2g=,tag:z2e0OmmqJ5hJ+69pSfikyA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
