apiVersion: v1
kind: Secret
metadata:
    name: demo-secret
    namespace: default
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:1bOVHKnA4wk=,iv:imbsrpbIIxP80QUBq2cLki9QeHDjt318SBRIG/Fi+28=,tag:kN6PpXd9ydV+kN3NZcELYQ==,type:str]
    password: ENC[AES256_GCM,data:dgrc/NvAOF0zzPTzDas=,iv:YYVToMw5sH3Jbq3maW8kzxkc/09Ugw2xvNQr+nf7qkI=,tag:3k4KCOjdhSn1W6r8gkL+lg==,type:str]
sops:
    age:
        - recipient: age1l554jhzkcyzu826w2a6nlczjzsfqgl29lwuntu9t3ydmfuwwucfqjgcyza
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEZEtFamo4ZkcrUkw1RVhC
            THg5bjhYKzJFK2h2a2pxcjIxb2k4YjBvY1RrCm93VWFMbVZTdnVENVRRdFZnZkpE
            WEdtdlNZNm1yZEtONklVSjQ3Nnd3azgKLS0tIExJcFZFTHo2YlptalNPWXFBRWNh
            d3AxMXBMQk9vR0Z4TXJZMTFuVi91NVUKmNuKfJR+M14SnHuuB6SMb0yI7Uq6mjRF
            2BWSLNi7RrycmMIFHjRP68WujScn+jMCJBskI6MrPwChC6xjSnnJog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T07:13:20Z"
    mac: ENC[AES256_GCM,data:ahC45YIRhtAa91tPSOEA/FsZwag4Ghs4D7iH9qEn2mr9tEpyZ6Xh21gNB13m8JAW1f3vivtWItdXbaYHrlwWa8W/yY1Kp6kw2dF6hS83hzKlfnNhaHY5sSCi+bnsD9hyS223scuAYAOuaRFxHliGiENe3gwpljkCEE4dVUqIeXA=,iv:bpMCkwElNlsUxdFnIXh78jaOYqb2Igr9cbMZh0+7WgQ=,tag:aVSVL0l3ipxnrqeSEhnw/g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
