apiVersion: v1
kind: Secret
metadata:
    name: demo-secret
    namespace: default
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:9V1R6Q==,iv:0C4movwR4C5rJmFNS+zUAum0rCLyec6ApntfK2+bBQg=,tag:U+na+9YwUKugA9ynXiLC5A==,type:str]
    password: ENC[AES256_GCM,data:ivtwJWAo3eGuQAE1MGk=,iv:tIl3ho+BySBjwrlc/bOdZDeA+CfiIdjZJlmWWaWC0FA=,tag:cHU/q7w2sXWNjY4VgbaqdA==,type:str]
sops:
    age:
        - recipient: age1l554jhzkcyzu826w2a6nlczjzsfqgl29lwuntu9t3ydmfuwwucfqjgcyza
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlL1RjaE4vWURIYXlaTXVP
            WC9vNElmQ2I0eXRwM2tJbjhjREE5NVFGM0NrCjU5VTBoM3BuRGFaa0E3RWNDNFJr
            V2I5a1owSERQYzdRMUNZRldUd3hZR3MKLS0tIDMwVHZoK0t6UUdEMjVGelo5cXZk
            L1Zzb0lDSFl1VDFNaysvOWRlRkVkdlEKdnZjj96G1INByVsJ6Q+6c5VzdIOCFLhg
            kuDIJm5f3uIbmijCgHYgysUK+eKykh4am/bUgDSJzldrLYibU2L5hw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T13:51:23Z"
    mac: ENC[AES256_GCM,data:DLJjkcsSb4Ob6X0ce693EzpUiLRQC0XxqG6Ij/DYMSIWfu5/NeVpZDCV5KJFHEVKjgucMRY6i6+hPqQ3i6rJaigQYkWr3GyPyODfJbDxtV+nNU7b/iSW7ml49rfTdxdjs7zqziq4/F/5ST+uHbPnBw/ujteKAPFfiZPUzdCDXHE=,iv:8ZCWhgdbUlTahohFEk+YERQuwtsGuQVFeBzZ2c0HAqI=,tag:xb9O1jI8qRbIvIHEcWTRjg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
