apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - demo-secret.sops.yaml
  - n8n.sops.yaml
  - postgres.sops.yaml
  - postgres-backup.sops.yaml
  - postgres-n8n-auth.sops.yaml
  - actual.sops.yaml
  - linkding.sops.yaml
  - analytics-s3-k8s.sops.yaml
