apiVersion: v1
kind: Secret
metadata:
    name: linkding-secret
    namespace: apps-linkding
type: Opaque
stringData:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:9487Ae8=,iv:YvO2Xd08RiIwj6bicrPhxjWDS6di/IDU7jO6Aknqq44=,tag:CgzpYRqP/q52ADUq17wZpQ==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:aVgiKojdXEb2bTu1,iv:noZ3DzSsVaE/hui4AlJr9oPWH0G2pll8OdjS8VqEKiY=,tag:35JsUubfbV/nvoaXlrPdQQ==,type:str]
sops:
    age:
        - recipient: age1l554jhzkcyzu826w2a6nlczjzsfqgl29lwuntu9t3ydmfuwwucfqjgcyza
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFUDhXTGVrUEdwVGJsR0o3
            cnQzQjdmRncrdUlMaVVORU1DbjAwTWZMVldzCmFRYU03NEtKMXExMXY5ZmJYeGZC
            dk9PN0srWXQrU3RJZU81R1ovTXBCUUUKLS0tIFdpbVREdG9KRkJ4K1p4YTBWc0Nv
            VENQT0c0TCtHVklsUFo0M3FjZzNqUFEKhvW0qAlQVEZmCxMMQIuRf9Iih76ndkh7
            GsEiyHK03BsYyaoZZMMhDf26H6FSC9Q18cIV0hmvU/7M/3qoYUVEtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-29T16:24:17Z"
    mac: ENC[AES256_GCM,data:bSBvaI2aTfQnvV7qEIKJeQ/2c4nZezpfVMmAE22cQEh9pKtV31dFiQ+d3zcpF4K2DfknhJHBOdhE9r4a14BOhXM7iCgrDHzCKHmcuR1yvlGK4sa+g6jUZMkwVEJMaNWM4+MI2GiosPwbbUzesccuVoqXNTrJm+lb/zx77WHsXpc=,iv:NYQ3RZWDPeZavPVCV44dP02VjpNoktYLUEx4lC9Kiw4=,tag:S91byGid3zH/IWJhAfHNNQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
