apiVersion: v1
kind: Secret
metadata:
    name: n8n-secret
    namespace: apps-n8n
type: Opaque
stringData:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:xCLYKHQn83DPV8H+q6cG66G1xvYNrOFNkvYbExmkPWM=,iv:iIJ3ik2kd8v87DM9Snle0p4wakAObX0dn4XyJ2HFS6g=,tag:zj8QDOGsl+YTAYZi5Q9/NQ==,type:str]
    DB_POSTGRESDB_PASSWORD: ENC[AES256_GCM,data:qgRQvyi8RNDaxBCBeJu4iaR0,iv:xUqq25LViN2AD3G8bakbk6E6BnJAL05E8sGvQHMcZ4U=,tag:xdwxrB6L26LkYO8G9fadLA==,type:str]
    N8N_BASIC_AUTH_USER: ENC[AES256_GCM,data:NdKdXxE=,iv:gJk7elNMPccgVYFvJmQA980tnU3ozwfhgDQAvWPf694=,tag:LmZJU/U9XNX8fHNP6ttQuw==,type:str]
    N8N_BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:Q3uC6NO89A3GkLAL,iv:HiUhO3VocZpAps4FMAy18Cb6kFrXqGXXZmYGkKMxtYU=,tag:pSsS2V9OZRIjU8FnxMfuUg==,type:str]
sops:
    age:
        - recipient: age1l554jhzkcyzu826w2a6nlczjzsfqgl29lwuntu9t3ydmfuwwucfqjgcyza
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZlMyTXRtemM1ZWlEQytX
            SUYvSlp5c1cyZW9ZZzBOZmFlc1pUaldoakQwCnBCUVo5K0VUU0pHL1pBakZnUU4r
            ZHE0Rk5uUkE2SWtKa090R3MxbVFvd0kKLS0tIHdLRks3SXVyaXRzWFQ3UlVYejE2
            ME5EcHduRlpkWXFnNTY5bDNiL0Q4Y1UKv+v1mWgsHsxu/6UPmcNmS1GPcyhjOfpt
            YGOjYsCDJA6GnXL278oqNrZi+f/avFgFaDwHCPLpHRSQyLiBixEOyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T09:42:42Z"
    mac: ENC[AES256_GCM,data:a/NxbvUTkZY4Ig+RkhGQjqGAENVAdpwFtgfRqzMMovLbEvuHr7OHazzE9lnVxK9ZooMp0kgeanm8Al3Pl3DrLR/NQCw42xVj/7IzG5j59x5Y+03GqN/K1jkH4aFhdfAIusCdExMwr3T4dJJFLaJUmyi4kF93m/FhL9OsbiRoRqM=,iv:Mwf5I0njgdQmuYeFYXqQbOvs/Bp3h4DsWLEHaRsQlNY=,tag:/GrFQUpD62UUF5UUDTBvEA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
