apiVersion: v1
kind: Secret
metadata:
    name: n8n-secret
    namespace: apps-n8n
type: Opaque
stringData:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:+tofnsIBU7qP7U4wYrWVrM7+dHgGfwbiWoxqgVRRbNo=,iv:iI3tK0xftleYwhyrKnwHhCSNHYmt9dhN9KGnzbVlMz0=,tag:GeYHTISeVj402TCAcxpHcg==,type:str]
    DB_POSTGRESDB_PASSWORD: ENC[AES256_GCM,data:ToSR1TYxvTp3Ft8ZHyylZXAv0D4=,iv:pqaueiGnRDW/Zu0k66r2YSmx+EC1Vy4o+E0SYq1HtNs=,tag:obW+98mjzDO8nVCZDJa1lw==,type:str]
    N8N_BASIC_AUTH_USER: ENC[AES256_GCM,data:Q6EJwFU=,iv:GzumEzxpgGZeSFK1oXyZK3Oyjxbzde1yQo4yCWsZPyA=,tag:Z5eUAtti/oh647JndwS01A==,type:str]
    N8N_BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:SeMsO84bGOUOdt9e,iv:m0jpw9hlVOZxOISsIuauIL1v7xdxV9fqor9KmqtREVM=,tag:onj0fP4pv9M4/lZlvRwvGg==,type:str]
sops:
    age:
        - recipient: age1l554jhzkcyzu826w2a6nlczjzsfqgl29lwuntu9t3ydmfuwwucfqjgcyza
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCeTFzSm91MXZhbVVpODNU
            Ny9ieUJ3UHphMHZhdGNDdEdZQVo4UTJBdHpZCmJqZzlUK3hucXJGUnlRT0M1L0pV
            UmtMRHA3TkFWejZHMXN6NmdoUlRTRG8KLS0tIDE1Y2RZRWxJSDJrNmt5d1RBcjhT
            RURVRmxsSHhwemZJY0R5K0RYMkdCamMKFoGbi/EcfdLIvI9qwb2YjSTkxr+8LtiE
            bv+I+JWGTgIVdN9eOSM4EZdhZEGMv9RaA+9nei3dntLUhonDGumy7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T08:22:39Z"
    mac: ENC[AES256_GCM,data:TIRa9mj31x4omRVOjWC+U1g4VKSEmG+ZWbUEzdmu8CLN0w+W6FGlaCe7oSGRzHSDvDedHZEfcBrl67BXSeTQMri1OqiwZpuh96NCVFLJp0BhJl0BDI7ppqUsae9eOQuFxpIi6/QW7ioua5jREmioGqfk+LxwXKwSHUsT6x2mKVI=,iv:VVKNAz9gTT/NmuhBLa44hQzQN3r79bMG7aza7x/ur90=,tag:DlpzTI7rg6C0S9baF5QqyA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
