apiVersion: v1
kind: Secret
metadata:
    name: postgres-backup-s3
    namespace: infra-postgres
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:RYY3En+RywHT5oLAjEVhPfFLtJY=,iv:CVza6HdpbswQzzzXXBHSAfGyy4UL1PIsR+kbHLM4n/k=,tag:aO6gEgTSl2IX5+bt/U//Dg==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:Gs183gLorS+N5ERI2jxxpm4bvBDpBxwpYR6zHS0HxLaMh3elVu1P+A==,iv:sikXoh+98jVF+AfMIw1YfdPmNb3pymA4k4jc0MoGm0k=,tag:bMimimJQZoLTfY1CQ/flGw==,type:str]
sops:
    age:
        - recipient: age1l554jhzkcyzu826w2a6nlczjzsfqgl29lwuntu9t3ydmfuwwucfqjgcyza
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZRVBSbTg2S1RtQ2w3c2dp
            UTAxdFo2TVo4cDAvT0RCVUpuRE1qRlUzbVZjCitKN2pLcEJUSmFYdHFTcUQ3VzVp
            TGZONmNFOVJGRXoySmwrOUNjcU4vOFkKLS0tIGNLaEMwdUE0MkoreWszUXlWTU1k
            RHJuTERJY0s3L3VZVGg2cElnRlpZaDgKBjTltCO/6FL7vuJyRtSKGEukZG00u0xd
            gVNT61gqbBJLvHXyD+1xaGdeMRIdDqyL3qf6HjHK7VOO4Rme9s5mHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-03T08:36:38Z"
    mac: ENC[AES256_GCM,data:eBGXDpeZqmERleYPmHN1ufWtm1gUTSVvRcGmGvKKL7bbLY87/MrYH/LwKeDiHM0sAvOhcEHGEgjRu/NPJ+qWA7H8UocaI86TMu9CIxz096icQN0MHo0r7hYmLqg2m3c5R7Rrga43C4lNHTtI971zxkiQMnspmHivWsTIwk7saIw=,iv:Du3Yq2EbFKJL3oYBg3H4cqvBgkbV0Ll9hHRdbfyXnE0=,tag://rqIGmTnMXJIpw7apFTNQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
