apiVersion: v1
kind: Secret
metadata:
    name: postgres-n8n-auth
    namespace: infra-postgres
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:8Jaq,iv:dKqhyj8TG7Y6crNu/dursN7RGDykbP+jRdDpwoGyMbg=,tag:R+DDWpF4iUiunAkU4YFmKQ==,type:str]
    password: ENC[AES256_GCM,data:bU3UEzA2l23AoeE9QUN0DyXwsm0=,iv:W5g+TIbg4reL/7f7BFCykic7YivO4o5tvm8LAJcRvhA=,tag:9gW3IJBvEpwqjJ654ql4ig==,type:str]
sops:
    age:
        - recipient: age1l554jhzkcyzu826w2a6nlczjzsfqgl29lwuntu9t3ydmfuwwucfqjgcyza
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGeXl4REVvdVV6ZDFWb0FK
            anBldDA3VFFXMTZNTXJOZURZZHJoM05ReWhvCnpVeWFnamN4TlRIZ2VzenhzUGEw
            MENpS1JBY0ZKUExTZDBWU3FFMkQxQ0kKLS0tIEU2KzZEMXdWbTBCV3JsNlpUMWE5
            N3JXMWZWZEFxYUROOWt3Q3VFeUw5RGMKeG/Ju7EKK7QcykP1R4UK+JqzVTEEcsba
            u8FWH4NXkyBaac0UHhFFTrf305OgVAqB0Oq10H3sGC5WNBzmiNCunA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T08:23:42Z"
    mac: ENC[AES256_GCM,data:Vy/k9ycwAf8En5IvQsxe/cYtLRO7ycu8Udes2breiMd5y33DRoBXupe4dN3SeSOC1wpP2g8dMVjU2lJFIXGs2raOZBMkp/10bz/bC9SqGiE6x158tgWj9oah581YxWl9TgxsYVduxJs+cpr5jA44lu2T11bkKdKS5DEsp62HkA0=,iv:AvQgjsChsAiDUb8oFPKn7MIyZ7348wCmSV+Hks6zN7k=,tag:UI8qmlxZaZwDvCrP7jgf3A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
