apiVersion: v1
kind: Secret
metadata:
    name: postgres-auth
    namespace: infra-postgres
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:HoXL8UTmV0NSYs0F,iv:IDOyFWKciq9rR9Zo0d/7iAdxqRV/knc0OuD8gLrMQEA=,tag:zciOLXNrMZh2Jc4C0i2Q2A==,type:str]
    password: ENC[AES256_GCM,data:lNcXeVKs2brS3P47so5Tvg==,iv:SsJOapBa0KB4HuUSMcihwBZHqkAhwiHp7/lDF8S91dc=,tag:A54ZUEUAMvcZ17hqpX1D4g==,type:str]
sops:
    age:
        - recipient: age1l554jhzkcyzu826w2a6nlczjzsfqgl29lwuntu9t3ydmfuwwucfqjgcyza
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhU2NsNU1Pbm1SQzV3b2xS
            ZVJ0MzgrRHNORjVYWkVhZWQ5MnZwZDRkSlZnCkM0R1JiYm5Cd0VVZkJZWkxCa1Zl
            V1p5cndFK3JhQmI4eTFsdVd5NU8zMG8KLS0tIDlKVTJMNHdYWU1pQXJNS3RudTMv
            RWwrRzQ1bnZjYWxLWnJua1RER3E4bmsKyqAqLCx0hGkgSpH/a0gvbzHZZ16ziKmA
            spmdmj1nQxN5UpCK50MfHO2JxrMU/2LBiyWE8ft0n+ZGYqTAZ/UhGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T07:27:03Z"
    mac: ENC[AES256_GCM,data:OPcFFw52sKr6fji3xZbpF2rxQ/a23cEYqLCZ4VF3JvMDGXc6TyohhNNKzWKowBDXdOy2+2RUVygSzpyhwZnoUOBTHHLFlxxUimrPEw2uaYS1lwdbaVZxLtLf0DdKnQYrWYJkKeEHVpGZQt5Ac+zBX+2HgBvJVUPoK/N9hVNLt10=,iv:MOGXWjxeIWB8y/iO4h08tkGr3OLUl6gmCmBvVtZx6Wg=,tag:gpNvAO9SCSCUY/iv5M1j4A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
