apiVersion: v1
kind: Secret
metadata:
    name: postgres-auth
    namespace: infra-postgres
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:P476rEBcWw4UjzqXQUJxzA==,iv:4nBqzZhQEWUoBjArpcLj30vkGZcdo0w4pHkGDOFZbnM=,tag:zfiHZLGTtdVYLbi2FD6y7Q==,type:str]
    username: ENC[AES256_GCM,data:Yiva,iv:N+QGwBsQw8aYop+RweL7ce5s9/cUSA9818QvtUSzpEw=,tag:KsX7Uf6FJ7Xvo+6sN6aIJw==,type:str]
    password: ENC[AES256_GCM,data:6EqKGLP5GuJAUZWa24mDGw==,iv:QDWN059faLwtYEfK16dXqAxYAMYMa3S1NNbi2aL8b9U=,tag:X0UZSHrz0oA9KeQplrIQlw==,type:str]
    database: ENC[AES256_GCM,data:dZgB,iv:T9uNCJ1DLUr3YQ6miityd7RYVKL03qZxDbAywPrSx8w=,tag:m9xI1XuNLnhHOKQoC+72gw==,type:str]
sops:
    age:
        - recipient: age1l554jhzkcyzu826w2a6nlczjzsfqgl29lwuntu9t3ydmfuwwucfqjgcyza
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyKzJQOU12a1ZqeDJqWGlp
            QVhDQmdFVkwxSzFmSTYrRS8xeS9GTTJxcVg0Cmw4V0VmeCszNVEycEdqMmZhRjM2
            aXdFWWNYM2ZyYUJhcUFLaG5GWk5TZG8KLS0tIDNMTWxCcVV2U3VIQlNHUi9QSFdo
            bDFpcTV2NlBkMk9yUnJ5S3cyT2FBK2sKcl/6qodoe38Iyq9w08vUdKCKAA1yO4PF
            y65khSZF3bXpvs2wxPyCK7ljzUF9RRi5avpB7Wrp3G3IPkSMK/6+Xg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T16:22:03Z"
    mac: ENC[AES256_GCM,data:vkWnxTBoijLaYlzIgYGNzx8BjF7zcv/256qhMR77jb4WDBOtDHn5boL2KXqokyy4sUTE7rJJmjfWF/ms0rKOEWyOOC+iO5QU1Gvyf+AyCnLZKlGfgtTCV9HQ+H1IKaumkGdIYEP+zSZfX8WB/1JvGpuW2WTkYMPXsOIlV/IfGbs=,iv:ibTwJ7mHy151td7yU2uFpL7Yvx/5TA/3AWWikaOTXU8=,tag:JDwpMtv0UYN5n9HpiNTYbg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
