apiVersion: v1
kind: Secret
metadata:
    name: postgres-backup-s3
    namespace: infra-postgres
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:F5biJ+yjELt+F8OIBk21pTHmAFs=,iv:+hcBiDyl1zz/WKehaggtuPRMUbvuq2CNg0Q62U/DUA4=,tag:6Z2ZNl1OyXFZ4S1oO+h45g==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:kSJQ1cMXbFcpjAKfMKBaffB4sLElAtn8eeR8zE7gcOZ8NKBYVqYbuA==,iv:cLBZ/3y7UPyb/YFEMHUR+iYbF7Ra9HVNVFrjAQr9clM=,tag:OtADpKNjVlAViQiX3OdTDQ==,type:str]
sops:
    age:
        - recipient: age1l554jhzkcyzu826w2a6nlczjzsfqgl29lwuntu9t3ydmfuwwucfqjgcyza
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlRVRTYmM5Q3R2RlBXcjJS
            MU5iOVFzYUVwcmVENVhsRXRZZlF3WDduUTNBCnBraDdaa3BRSGdtdjhVN3lsUjBo
            ZHhXemxra25haVJBNjNDZVRSMVFzSVEKLS0tIFlVK3g1NTMxZkRZU0dJSUxwTktL
            Yi9QOVB0UGE5d3ZKdVovdnV1b2E3R00KjmdwV1ccwbGZXhT+0/uY8bdoNFUpngTN
            LztZarBEhI2usSFjt5kS47VOXBtv52DYXYaipiFBPTzE25sHTAaemA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T13:07:32Z"
    mac: ENC[AES256_GCM,data:JAsXZI5WDxBSaRYF3H2s4l6VsGS+6nKOXzSDh4bOMfYaTfoSUva9x7MHzrFR/HE2fi+6haHnpU196SRPshareAiLyAG4lVryEwXoBr1jWWiIacL9QevFvpejibZrTAkbbw31zzWPRYYu21rRE2Ih5IqIu7eIuGcLSdmcjCuGKw8=,iv:Dl0dL9QGbHMe6ccZNLCWLbDMPdw0vCvJ49QxUVaHSZE=,tag:4Ifo8R8qp8PXTbiwHmeTwQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
