apiVersion: v1
kind: Secret
metadata:
    name: postgres-n8n-auth
    namespace: infra-postgres
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:lUWx,iv:zxnD9AbeKTqAqHtZOm7J0Wd3GQU9il2Vr/L2iQuDJ3k=,tag:RHoyAzAbfXm3Vs40Q4lRxA==,type:str]
    password: ENC[AES256_GCM,data:dcN8AxJEJ+LVXuR0QQPbW9tYf68=,iv:aFVR+wO11h67Ar1eAk+B1Cbg/cO5dkSiSsJas29KlBs=,tag:Vh/1LNL7yh8NNIXPJtujNA==,type:str]
sops:
    age:
        - recipient: age1l554jhzkcyzu826w2a6nlczjzsfqgl29lwuntu9t3ydmfuwwucfqjgcyza
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuM3I1UE1TQnA2SHRmT2VF
            bU5abkZTVEZNTUtXWDdWZ2VrSmd1YThqQVU0CkI2M2RITnpCaEdlY1Z4aERVMkZu
            UHBjNUM1V1pIQkFSR3ZqajB4ZWx2RjQKLS0tIHlpS05xQ1EvajhmclZDbDFrL0VM
            SVB6K01pSUFNRy9tTlM1VEtzU1BkRW8K85a5H9EeDiznjxET5XGnvSd1iYQbmXTS
            J6U7a74EC1+wVQhSK8V/Vm9mgElHXz7VS/XglBLLGzzquhrBmMLaug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T08:44:53Z"
    mac: ENC[AES256_GCM,data:dzhWGuXzN4G48y72h7gbMw00Clt/ob2OoCT+dJl2d/qsPQT3tCYMnlQkHnhsfqj4jRdKv9+EabA3sRcTT+wCuDD27CtwJprIBWXnTkL/NgRT7pmKNdkOM1Ti/h2JEFm+r3z2aCffov0at4xa9LujTl7u25GfPmdwhg+XqFGNIm8=,iv:VMmiN/wvjnw1sFsJn1itlpTwLP1WfKA/uMl9mkiug8w=,tag:k3OFpzTF+44DZWnuYlRM+Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
