apiVersion: v1
kind: Secret
metadata:
    name: postgres-auth
    namespace: infra-postgres
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:2XSwFnuByXzPOr28,iv:qF78Zis+wXoV7Jb3Bqr++OuZTHBHOaW/RnSOJHLr9gg=,tag:ZY4C2SQNl/lsibag1FbIZA==,type:str]
    password: ENC[AES256_GCM,data:kj/QPq3xXFXMetN6pM/2FQ==,iv:diORpI/gqEtQeRJFaBJmET7D21AXha09swWIIN/70Ds=,tag:aQ+4jtZqWezu215WOO5D7Q==,type:str]
sops:
    age:
        - recipient: age1l554jhzkcyzu826w2a6nlczjzsfqgl29lwuntu9t3ydmfuwwucfqjgcyza
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqU1NyM2oyOU4vS2ZCKzBm
            TW5teEdtVURYMXBMRkVRejQvZHJtL3YzOWwwCnM1dzUrNStuL3FYMTFSS0M4RTNy
            dE1ZWmRJbUtDVGdtQys0QVE3VWU5R0kKLS0tIE9pOEEzZ3BBTW1DSXRLdDR4Tk5Y
            ekl4eGJsKzdyY3BCSXFVQUI5QjdxYWsKJb37wh9lDJCeJDC2ghNBvI8mJ2Ih3ynX
            CLlgkW4jZdJx/0lDQbNxifW9TYxSnEPMbimP4IxzcBZ3AsnB7OL/qg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T08:44:45Z"
    mac: ENC[AES256_GCM,data:ZtfYyJo7BPT8TowgsxDjNNwBMrV5IxKll0D3L3mJDQ30QFRnvEc93k+fNGFfqCv7QvnEr0nSyZFHMyfqehtedIGRH0Ax3/LfMesbUtvl2H4vyriGBcNBE45gf4XcVR7+VrBvButV8jgZ1VvtU+VvDLIvEsiOiAxG4lgWHpIATa0=,iv:pQkzI+FtZPJdTqHnWzuLQU6UJ4l6zJhGMMWHH4aXytk=,tag:CSfUElhBUjhg6GoxeyfNrg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
