apiVersion: v1
kind: Secret
metadata:
    name: postgres-backup-s3
    namespace: infra-postgres
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:n+Stxy9B3FgjwvX4TL/wxlPzLQg=,iv:vJybRVhqZn+u+yZZG2c0w5c9QiiWT7DmkxHH0ie/vaI=,tag:6vcXI9ZgZOlXMnYHZG9e/w==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:rCJqZFddONoI8LGqRYT4O0LTazZm1BIgutczDT7GcA8KpgHxFsHPLA==,iv:q3yosNS8w2DP0Bi29zBgtG0vAD2vPCFr05/o5SDStzk=,tag:mM3cyC/+uu8FklmVgy8a4A==,type:str]
sops:
    age:
        - recipient: age1l554jhzkcyzu826w2a6nlczjzsfqgl29lwuntu9t3ydmfuwwucfqjgcyza
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGc2NoNnl6L2Evdk54NUFE
            dTFvWnVWd0NvZEdidGFDNFo2cWJnZzZGV0hFCm54dXNpckNseFF4b3A0NTd4VVZT
            OXBPdEtpVUFMM053ZzZaVStacUtGWUEKLS0tIGFaaVI1WEhjV0QxRzJuMkVBRkhO
            OWVnQU9VTkxrSzEzVXpnczdnY2lBY1EK3p6crzj6Gb+LSOKS0n4IQVyzA6B1zFYG
            vT/IDo2BZRehSn61+0Agafu3wjzFwk4GVhTnorZkTHWk4j2IYfWjDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-03T08:20:15Z"
    mac: ENC[AES256_GCM,data:a/OWnFb4HbUS+dhixuH9ymwhadAaWnWpO9yL8HvJfmVJhsgsanLoHHauQQpktEMaorSFW8jKDurKEErI0ZT065H91kux2bc836vc9xO8jhOO2coIKPD5PQRudcKbI0rKRXq7NQhMO/Kp//SAvdXw2CDTRCGK3zWzkVgS+HtP9LY=,iv:3shiT3eqfn0JyHkSQ6YIio/2oyKWZj09eGMe5RDrqzo=,tag:0CxYgjlj/hGtR9kYcuNctQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
