apiVersion: v1
kind: Secret
metadata:
    name: postgres-n8n-auth
    namespace: infra-postgres
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:JnlN,iv:pMoIZENPukbEKWMzZVHM/wfDoY+lyc7u4v3OMNdyyos=,tag:BO4Pl27nQk8yuaumD19FpA==,type:str]
    password: ENC[AES256_GCM,data:liqH8G1oOxrLcPZPORIAPaYR,iv:ROXYUFBhn+Oh1ua0mafIkS2uQ8wgxZwHk1MizQAwMYA=,tag:db845/53hg3xBO8IxV6uEA==,type:str]
sops:
    age:
        - recipient: age1l554jhzkcyzu826w2a6nlczjzsfqgl29lwuntu9t3ydmfuwwucfqjgcyza
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzM0tWR1M5MCtBWVNpd3JW
            WkorUTBxNWNqakNPNExTM3NyM1Njc0luM0FvCnJyNVpnTThOMkFGNGFQNXBOYXkx
            VkZGL01Fa1ZmaXZsUEtpLzd3Yk9USFEKLS0tIDR5Z3RlV2pEcGRiMjZuaTI2RFpT
            Nmh6TGNuaVJXb3hTVUl0d2NsNXZlV1kKdXJ5y0ib3AhbR6f1fxr28sGdluEiJNsI
            AFcoG5HvP4Fp+20vpPf1wFnCyLvT30LC6+acF4ICvVQO74E9BCrn+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T09:42:53Z"
    mac: ENC[AES256_GCM,data:Bjiy5QRRBEDnXnR1TnEdrhc7YDahII/hQk0QxKrpJc8omflKDX57gMdjwXzouvSDL/99Lv4bztKpcpMeDt4TKWLzwW4aBLXT7yNEZAgeRFHy4mdPuLsex/dlKpLJowFO8sAH22meXQTQ+qAWcdfUw0VYNJIbNcGs4LWB5LE414s=,iv:17vTY3GS63ttAG5A0SBCEEqq1t5npyq5snHy8bn2nJs=,tag:046bxqhEEwgRKhUOYPnOsw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
