apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: analytics-collector
rules:
  - apiGroups: [""]
    resources: ["nodes", "pods", "events", "persistentvolumeclaims"]
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list"]
  - apiGroups: ["cert-manager.io"]
    resources: ["certificates"]
    verbs: ["get", "list"]