apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./flux-system
  - ./kustomizations/platform.yaml
  - ./kustomizations/cert-issuers.yaml
  - ./kustomizations/apps.yaml
  - kustomizations/secrets.yaml
