name: home_platform
version: "1.0.0"
config-version: 2

profile: home_platform

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

vars:
  analytics_history_days: 16

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"


models:
  home_platform:
    intermediate:
      +materialized: view
    marts:
      +materialized: table