apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkding
  namespace: apps-linkding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkding
  template:
    metadata:
      labels:
        app: linkding
        home-platform/analytics-collect: "true"
    spec:
      enableServiceLinks: false
      containers:
        - name: linkding
          image: sissbruecker/linkding:1.46.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
              name: http
          env:
            - name: LD_CSRF_TRUSTED_ORIGINS
              value: "https://links.titas.dev"
            - name: LD_SUPERUSER_NAME
              valueFrom:
                secretKeyRef:
                  name: linkding-secret
                  key: LD_SUPERUSER_NAME
            - name: LD_SUPERUSER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: linkding-secret
                  key: LD_SUPERUSER_PASSWORD
          volumeMounts:
            - name: data
              mountPath: /etc/linkding/data
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: linkding-data